[package]
name = "ffi_derive"
version = "0.2.1"
authors = ["Nicholas Smillie <nicholas@agrian.com>"]
edition = "2018"
repository = "https://github.com/agrian-inc/ffi_common"

[lib]
proc-macro = true

[dependencies]
ffi_common = { version = "0.2", registry = "agrian-registry" }
ffi_consumer = { path = "../ffi_consumer" }
ffi_internals = { version = "0.2", registry = "agrian-registry" }
heck = "0.3"
paste = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[build-dependencies]
ffi_common = { version = "0.2", registry = "agrian-registry" }
ffi_consumer = { path = "../ffi_consumer" }

[dev-dependencies]
chrono = "0.4"
uuid = { version = "0.8", features = ["v4"] }
